---
 apiVersion: apps/v1
 kind: Deployment
 metadata:
  name: mydemoapp
  labels:
   app: mydemoapp
 spec:
  replicas: 1 
  selector:
   matchLabels:
    app: mydemoapp
   template:
    metadata: 
     labels:
      app: mydemoapp
    spec:
     containers:
     - name: mydemoapp
       image: pratichidas/k8sdemo:tagversion
       ports:
       - containerPort: 8080

---
 apiVersion: v1
 kind: Service
 metadata:
  name: mydemoapp
 spec:
  type: LoadBalancer
  selector:
   app: mydemoapp
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
