---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: demogcrapp
 labels:
   app: demogcrapp
spec:
 replicas: 1
 selector:
  matchLabels:
   app: demogcrapp
 template:
  metadata:
   labels:
    app: demogcrapp
  spec:
   containers:
   - name: demogcrapp
     image: gcr.io/sincere-idea-275411/pratichidas/demogcrapp:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: demogcrapp
spec:
 type: LoadBalancer
 selector:
  app: demogcrapp
 ports:
  - protocol: TCP
    port: 5566
    targetPort: 8080
